extends Node

var flash_cards = {
	"words": ["Dog", "Hat", "Car", "Wall", "Bed", "House", "Books", "Bat", "Cup", "Plate", "Cherry", "Pineapple", "Mango", "Shoes", "Gloves", "Cow", "Fish", "Bird", "Apple", "Banana", "Orange", "Green", "Yellow", "Brown"],
	"illustration": ["res://assets/art/backgrounds/skill illustrations/identify/dog_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/hat_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/car_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/wall_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/bed_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/house_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/books_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/bat_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/cup_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/plate_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/cherry_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/pineapple_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/mango_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/shoes_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/gloves_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/cow_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/fish_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/bird_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/apple_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/banana_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/orange_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/green_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/yellow_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/brown_illust.png"]
}

var identify = {
	"words": ["Dog", "Hat", "Car", "Wall", "Bed", "House", "Books", "Bat", "Cup", "Plate", "Cherry", "Pineapple", "Mango", "Shoes", "Gloves", "Cow", "Fish", "Bird", "Apple", "Banana"],
	"illustration": ["res://assets/art/backgrounds/skill illustrations/identify/dog_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/hat_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/car_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/wall_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/bed_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/house_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/books_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/bat_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/cup_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/plate_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/cherry_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/pineapple_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/mango_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/shoes_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/gloves_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/cow_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/fish_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/bird_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/apple_illust.png", "res://assets/art/backgrounds/skill illustrations/identify/banana_illust.png"]
}

var story_time = {
	"words": ["Hat", "Wall", "Cat", "Cow", "Fish", "Cherry"],
	"sentences": ["Which word ends with the same sound as \"cat\"?", "Which word rhymes with \"ball\"?", "Which word has the \"a\" sound like in \"apple\"?", "What animal says \"moo\"?", "Which animal lives in water?", "Which fruit is red and round?"],
	"illustration": ["res://assets/art/backgrounds/skill illustrations/story time/hat_illust.png", "res://assets/art/backgrounds/skill illustrations/story time/wall_illust.png", "res://assets/art/backgrounds/skill illustrations/story time/cat_illust.png", "res://assets/art/backgrounds/skill illustrations/story time/cow_illust.png", "res://assets/art/backgrounds/skill illustrations/story time/fish_illust.png", "res://assets/art/backgrounds/skill illustrations/story time/cherry_illust.png"]
}
